/// Generated by AssetsRefGenerator on 2022/08/31
class Res {
  static const String String_instagram = "assets/001-instagram.png";
  static const String ajouter = "assets/002-ajouter.png";
  static const String cur = "assets/003-cur.png";
  static const String comme = "assets/004-comme.png";
  static const String cur_1 = "assets/005-cur-1.png";
  static const String camera = "assets/006-camera.png";
  static const String instagram_1 = "assets/007-instagram-1.png";
  static const String bulle = "assets/008-bulle.png";
  static const String bouton = "assets/009-bouton.png";
  static const String sac = "assets/010-sac.png";
  static const String diffuser = "assets/011-diffuser.png";
  static const String ajouter_1 = "assets/012-ajouter-1.png";
  static const String accueil = "assets/013-accueil.png";
  static const String notification = "assets/014-notification.png";
  static const String commentaire = "assets/015-commentaire.png";
  static const String messager = "assets/016-messager.png";
  static const String concert = "assets/concert.jpeg";
  static const String concert_heart = "assets/concert_heart.jpg";
  static const String recording_studio = "assets/recording_studio.jpg";
  static const String a = "assets/a.jpg";
  static const String send = "assets/instagram-direct.png";
  static const String save = "assets/enregistrer-instagram.png";
  static const String search = "assets/search-interface-symbol.png";
}
